// ─── Turpial Sound Marketplace — Mock Data ────────────────────────────────────
// Datos de demostración para maquetado. Reemplazar con llamadas a API en producción.

import type {
  MarketplaceUser,
  ProductListing,
  ServiceListing,
  MessageThread,
  CategoryMeta,
} from '@/types/marketplace'

// ─── Mock Users ───────────────────────────────────────────────────────────────

export const MOCK_USERS: MarketplaceUser[] = [
  {
    id: 'u1',
    name: 'Carlos Mendoza',
    initials: 'CM',
    role: 'seller',
    verified: true,
    rating: 4.9,
    reviewCount: 47,
    joinedAt: '2023-03-15',
    location: 'Caracas, Miranda',
    responseTime: '< 1 hora',
    bio: 'Músico profesional con 15 años de experiencia. Especialista en equipos de audio vintage.',
    completedDeals: 31,
  },
  {
    id: 'u2',
    name: 'Valeria Rojas',
    initials: 'VR',
    role: 'talent',
    verified: true,
    rating: 5.0,
    reviewCount: 23,
    joinedAt: '2023-08-01',
    location: 'Valencia, Carabobo',
    responseTime: '< 30 min',
    bio: 'Violinista de sesión. Egresada del Conservatorio Simón Bolívar. Géneros: clásico, jazz, latin.',
    completedDeals: 18,
  },
  {
    id: 'u3',
    name: 'Andrés Villegas',
    initials: 'AV',
    role: 'seller',
    verified: true,
    rating: 4.7,
    reviewCount: 12,
    joinedAt: '2024-01-20',
    location: 'Maracaibo, Zulia',
    responseTime: '< 2 horas',
    completedDeals: 8,
  },
  {
    id: 'u4',
    name: 'Sofía Álvarez',
    initials: 'SA',
    role: 'talent',
    verified: false,
    rating: 4.6,
    reviewCount: 9,
    joinedAt: '2024-06-10',
    location: 'Barquisimeto, Lara',
    responseTime: '< 3 horas',
    bio: 'Productora musical independiente. Especialista en reggaeton, pop latino y música urbana.',
    completedDeals: 5,
  },
  {
    id: 'u5',
    name: 'Miguel Torres',
    initials: 'MT',
    role: 'talent',
    verified: true,
    rating: 4.8,
    reviewCount: 34,
    joinedAt: '2022-11-05',
    location: 'Caracas, Distrito Capital',
    responseTime: '< 1 hora',
    bio: 'Técnico de sonido live y estudio. Más de 200 eventos realizados. Monitor, FOH y grabación.',
    completedDeals: 27,
  },
  {
    id: 'u6',
    name: 'Buyer Demo',
    initials: 'BD',
    role: 'buyer',
    verified: true,
    rating: 4.5,
    reviewCount: 3,
    joinedAt: '2025-01-01',
    location: 'Caracas',
    completedDeals: 2,
  },
]

// ─── Product Listings ─────────────────────────────────────────────────────────

export const MOCK_PRODUCT_LISTINGS: ProductListing[] = [
  {
    id: 'p1',
    type: 'product',
    title: 'Guitarra Eléctrica Fender Stratocaster Player Series',
    description:
      'Stratocaster Player Series en color Polar White. Pastillas Alnico 5 originales, afinación perfecta. Incluye estuche rígido Fender. Comprada en Miami, uso moderado de estudio.',
    category: 'instrumentos-usados',
    subcategory: 'Guitarras eléctricas',
    price: 680,
    currency: 'USD',
    condition: 'used-like-new',
    images: ['/images/artista9.jpg'],
    seller: MOCK_USERS[0],
    status: 'active',
    createdAt: '2026-03-20',
    location: 'Caracas, Miranda',
    tags: ['fender', 'stratocaster', 'guitarra eléctrica', 'usa'],
    badge: 'VERIFICADO',
  },
  {
    id: 'p2',
    type: 'product',
    title: 'Interface de Audio Focusrite Scarlett 2i2 (4ta Gen)',
    description:
      'Interface USB de última generación. 2 entradas combo XLR/TRS con preamplificadores Air. Ideal para grabación profesional en home studio. Sin uso, caja sellada.',
    category: 'audio-pro-estudio',
    subcategory: 'Interfaces de audio',
    price: 175,
    currency: 'USD',
    condition: 'new',
    images: ['/images/estudio-grabacion3.jpg'],
    seller: MOCK_USERS[2],
    status: 'active',
    createdAt: '2026-03-28',
    location: 'Maracaibo, Zulia',
    tags: ['focusrite', 'scarlett', 'interface', 'grabación', 'home studio'],
    badge: 'NUEVO',
  },
  {
    id: 'p3',
    type: 'product',
    title: 'Pack Cuerdas Ernie Ball Regular Slinky x 12 unidades',
    description:
      'Pack mayorista de cuerdas para guitarra eléctrica calibre .010–.046. Nickel Wound, lote de 12 sets. Importadas directamente de USA.',
    category: 'consumibles',
    subcategory: 'Cuerdas de guitarra',
    price: 72,
    currency: 'USD',
    condition: 'new',
    images: ['/images/estudio-grabacion8.jpg'],
    seller: MOCK_USERS[0],
    status: 'active',
    createdAt: '2026-04-01',
    location: 'Caracas, Miranda',
    tags: ['ernie ball', 'cuerdas', 'guitarra', 'consumibles'],
  },
  {
    id: 'p4',
    type: 'product',
    title: 'Batería Pearl Export EXX 5 piezas — Alquiler por día',
    description:
      'Batería completa Pearl Export EXX. Incluye bombo 22", redoblante 14", toms 10", 12", 16". Set de platillos Zildjian A Custom. Disponible para ensayos, grabaciones y eventos.',
    category: 'alquiler-equipos',
    subcategory: 'Baterías',
    price: 45,
    currency: 'USD',
    condition: 'used-good',
    images: ['/images/estudio-grabacion12.jpg'],
    seller: MOCK_USERS[2],
    status: 'active',
    createdAt: '2026-03-15',
    location: 'Valencia, Carabobo',
    tags: ['pearl', 'batería', 'alquiler', 'event'],
    rentalAvailable: true,
    rentalPricePerDay: 45,
    rentalMinDays: 1,
    badge: 'ALQUILER',
  },
  {
    id: 'p5',
    type: 'product',
    title: 'Micrófono Shure SM7B — Nuevo sellado',
    description:
      'El micrófono dinámico cardioid preferido por podcasters, vocalistas y locutores de todo el mundo. Respuesta plana y cálida. Filtro interno para pop y vibración.',
    category: 'audio-pro-estudio',
    subcategory: 'Micrófonos',
    price: 395,
    currency: 'USD',
    condition: 'new',
    images: ['/images/estudio-grabacion15.jpg'],
    seller: MOCK_USERS[0],
    status: 'active',
    createdAt: '2026-04-02',
    location: 'Caracas, Miranda',
    tags: ['shure', 'sm7b', 'micrófono', 'podcast', 'vocal'],
    badge: 'NUEVO',
  },
  {
    id: 'p6',
    type: 'product',
    title: 'Piano Digital Yamaha P-125 con soporte y pedal triple',
    description:
      'Piano digital portátil con 88 teclas pesadas GH. Sonido CFX Concert Grand. Incluye soporte L-125 y pedal triple LP-5A. En perfecto estado, usado en estudio.',
    category: 'instrumentos-usados',
    subcategory: 'Pianos digitales',
    price: 520,
    currency: 'USD',
    condition: 'used-good',
    images: ['/images/artista5.jpg'],
    seller: MOCK_USERS[2],
    status: 'active',
    createdAt: '2026-03-10',
    location: 'Barquisimeto, Lara',
    tags: ['yamaha', 'piano digital', 'teclado'],
  },
]

// ─── Service Listings ─────────────────────────────────────────────────────────

export const MOCK_SERVICE_LISTINGS: ServiceListing[] = [
  {
    id: 's1',
    type: 'service',
    title: 'Violín de Sesión — Clásico, Jazz & Latin',
    description:
      'Grabaciones profesionales de violín para tu producción. Mando mis tracks en 24-bit WAV con múltiples tomas. Experiencia en orquesta, cuarteto de cuerdas, pop y salsa. Estudio propio.',
    category: 'musicos-sesion',
    subcategory: 'Cuerdas',
    priceFrom: 80,
    priceTo: 250,
    currency: 'USD',
    priceLabel: 'por sesión',
    deliveryDays: 3,
    talent: MOCK_USERS[1],
    status: 'active',
    createdAt: '2026-02-14',
    tags: ['violín', 'sesión', 'cuerdas', 'clásico', 'jazz'],
    instruments: ['Violín'],
    genres: ['Clásico', 'Jazz', 'Salsa', 'Pop Latino'],
    portfolio: ['/images/artista2.jpg'],
    badge: '5 ESTRELLAS',
  },
  {
    id: 's2',
    type: 'service',
    title: 'Producción Musical Urbana — Beat + Arreglo + Mezcla',
    description:
      'Produzco tu canción de principio a fin. Composición de beat, arreglo completo de instrumentos, mezcla y masterización básica incluida. Géneros: reggaeton, trap, R&B, afrobeats.',
    category: 'productores-arreglistas',
    subcategory: 'Productores urbanos',
    priceFrom: 150,
    priceTo: 400,
    currency: 'USD',
    priceLabel: 'por canción',
    deliveryDays: 7,
    talent: MOCK_USERS[3],
    status: 'active',
    createdAt: '2026-01-30',
    tags: ['producción', 'beat', 'reggaeton', 'trap', 'urbano'],
    genres: ['Reggaeton', 'Trap', 'R&B', 'Afrobeats'],
    portfolio: ['/images/artista4.jpg'],
    badge: 'RECOMENDADO',
  },
  {
    id: 's3',
    type: 'service',
    title: 'Técnico de Sonido Live — FOH & Monitor',
    description:
      'Operador FOH y monitor para conciertos, eventos corporativos, bodas y festivales. Manejo de consolas Yamaha CL, Allen & Heath DLIVE, Midas. Rider técnico disponible.',
    category: 'tecnicos-audio-iluminacion',
    subcategory: 'Técnicos de sonido',
    priceFrom: 120,
    priceTo: 350,
    currency: 'USD',
    priceLabel: 'por evento',
    talent: MOCK_USERS[4],
    status: 'active',
    createdAt: '2026-03-05',
    tags: ['técnico', 'sonido', 'live', 'FOH', 'monitor', 'evento'],
    portfolio: ['/images/estudio-grabacion5.jpg'],
    badge: 'TOP VENDEDOR',
  },
  {
    id: 's4',
    type: 'service',
    title: 'Banda Versátil para Bodas y Eventos Corporativos',
    description:
      'Cuarteto de músicos de sesión formado para eventos. Repertorio de 200+ temas: salsa, bolero, pop, bossa nova, vallenato. Equipo de sonido propio de 5kW. Disponibles en todo el país.',
    category: 'bandas-eventos',
    subcategory: 'Bandas versátiles',
    priceFrom: 500,
    priceTo: 1200,
    currency: 'USD',
    priceLabel: 'por evento (3–4 horas)',
    talent: MOCK_USERS[1],
    status: 'active',
    createdAt: '2026-02-20',
    tags: ['banda', 'boda', 'evento', 'salsa', 'bolero', 'versatil'],
    genres: ['Salsa', 'Bolero', 'Pop', 'Bossa Nova'],
    portfolio: ['/images/artista1.jpg'],
  },
  {
    id: 's5',
    type: 'service',
    title: 'Arreglista — Orquestación para Cine y Publicidad',
    description:
      'Orquestaciones para score cinematográfico, jingles publicitarios y música de videojuegos. Notación en Sibelius/Finale. Librerías: Spitfire, EastWest, Cinematic Studio.',
    category: 'productores-arreglistas',
    subcategory: 'Arreglistas orquestales',
    priceFrom: 200,
    currency: 'USD',
    priceLabel: 'por minuto de música',
    deliveryDays: 14,
    talent: MOCK_USERS[3],
    status: 'active',
    createdAt: '2026-03-18',
    tags: ['arreglista', 'orquesta', 'cine', 'publicidad', 'score'],
    genres: ['Cinematográfico', 'Publicidad', 'Videojuegos'],
    portfolio: ['/images/estudio-grabacion20.jpg'],
  },
  {
    id: 's6',
    type: 'service',
    title: 'Guitarrista de Sesión — Rock, Blues, Funk & Jazz',
    description:
      'Pistas de guitarra eléctrica y acústica en alta calidad. Equipos boutique: Fender Custom Shop, PRS CE24, amplificadores Matchless y Vox. Grabación directa o reamping incluido.',
    category: 'musicos-sesion',
    subcategory: 'Guitarras',
    priceFrom: 60,
    priceTo: 180,
    currency: 'USD',
    priceLabel: 'por pista',
    deliveryDays: 2,
    talent: MOCK_USERS[4],
    status: 'active',
    createdAt: '2026-04-01',
    tags: ['guitarrista', 'sesión', 'rock', 'blues', 'funk', 'jazz'],
    instruments: ['Guitarra eléctrica', 'Guitarra acústica'],
    genres: ['Rock', 'Blues', 'Funk', 'Jazz'],
    portfolio: ['/images/artista7.jpg'],
  },
]

// ─── Categories Metadata ──────────────────────────────────────────────────────

export const PRODUCT_CATEGORIES: CategoryMeta[] = [
  {
    id: 'instrumentos-nuevos',
    label: 'Instrumentos Nuevos',
    description: 'Compra instrumentos nuevos con garantía',
    icon: 'Music',
    accent: 'gold',
    listingCount: 24,
  },
  {
    id: 'instrumentos-usados',
    label: 'Instrumentos Usados',
    description: 'Equipos de segunda mano verificados',
    icon: 'Guitar',
    accent: 'cyan',
    listingCount: 67,
  },
  {
    id: 'audio-pro-estudio',
    label: 'Audio Pro & Estudio',
    description: 'Interfaces, micrófonos, monitores, DAW',
    icon: 'Mic2',
    accent: 'gold',
    listingCount: 41,
  },
  {
    id: 'consumibles',
    label: 'Consumibles',
    description: 'Cuerdas, parches, cables, baquetas',
    icon: 'Layers',
    accent: 'cyan',
    listingCount: 89,
  },
  {
    id: 'alquiler-equipos',
    label: 'Alquiler de Equipos',
    description: 'Arrienda baterías, PAs, luces y más',
    icon: 'Package',
    accent: 'gold',
    listingCount: 18,
  },
]

export const SERVICE_CATEGORIES: CategoryMeta[] = [
  {
    id: 'musicos-sesion',
    label: 'Músicos de Sesión',
    description: 'Guitarras, teclados, cuerdas, vientos, percusión',
    icon: 'Headphones',
    accent: 'cyan',
    listingCount: 55,
  },
  {
    id: 'bandas-eventos',
    label: 'Bandas para Eventos',
    description: 'Bodas, corporativos, festivales, fiestas',
    icon: 'Users',
    accent: 'gold',
    listingCount: 22,
  },
  {
    id: 'tecnicos-audio-iluminacion',
    label: 'Técnicos de Audio/Iluminación',
    description: 'FOH, monitor, lighting designer, backline',
    icon: 'SlidersHorizontal',
    accent: 'cyan',
    listingCount: 33,
  },
  {
    id: 'productores-arreglistas',
    label: 'Productores & Arreglistas',
    description: 'Producción musical, orquestación, mezcla',
    icon: 'Radio',
    accent: 'gold',
    listingCount: 29,
  },
]

// ─── Mock Chat Thread ─────────────────────────────────────────────────────────

export const MOCK_THREAD: MessageThread = {
  id: 'thread-001',
  listingId: 'p1',
  listing: MOCK_PRODUCT_LISTINGS[0],
  participants: [MOCK_USERS[5], MOCK_USERS[0]],
  createdAt: '2026-04-02T10:00:00Z',
  updatedAt: '2026-04-02T14:35:00Z',
  messages: [
    {
      id: 'm1',
      threadId: 'thread-001',
      senderId: 'u6',
      senderName: 'Buyer Demo',
      senderInitials: 'BD',
      content: 'Hola Carlos! Vi tu Stratocaster y me interesa mucho. ¿Está disponible esta semana?',
      type: 'text',
      createdAt: '2026-04-02T10:02:00Z',
      read: true,
    },
    {
      id: 'm2',
      threadId: 'thread-001',
      senderId: 'u1',
      senderName: 'Carlos Mendoza',
      senderInitials: 'CM',
      content: 'Hola! Sí, está disponible. La tengo en perfecto estado, con todos los ajustes al día. ¿Tienes alguna pregunta sobre el instrumento?',
      type: 'text',
      createdAt: '2026-04-02T10:18:00Z',
      read: true,
    },
    {
      id: 'm3',
      threadId: 'thread-001',
      senderId: 'u6',
      senderName: 'Buyer Demo',
      senderInitials: 'BD',
      content: '¿La acción del mástil está cómoda para tocar con dedal? ¿Cuándo fue la última vez que le cambiaste las cuerdas?',
      type: 'text',
      createdAt: '2026-04-02T10:25:00Z',
      read: true,
    },
    {
      id: 'm4',
      threadId: 'thread-001',
      senderId: 'u1',
      senderName: 'Carlos Mendoza',
      senderInitials: 'CM',
      content: 'La acción está configurada en 2mm graves / 1.5mm agudos. Cuerdas Ernie Ball .010 nuevas hace 2 semanas. Te la puedo mostrar por videollamada antes de cerrar.',
      type: 'text',
      createdAt: '2026-04-02T11:40:00Z',
      read: true,
    },
    {
      id: 'm5',
      threadId: 'thread-001',
      senderId: 'u6',
      senderName: 'Buyer Demo',
      senderInitials: 'BD',
      content: 'Perfecto. Me convence. ¿Puedes enviarme la cotización formal?',
      type: 'text',
      createdAt: '2026-04-02T14:20:00Z',
      read: true,
    },
    {
      id: 'm6',
      threadId: 'thread-001',
      senderId: 'u1',
      senderName: 'Carlos Mendoza',
      senderInitials: 'CM',
      content: 'Con gusto. Aquí tienes la cotización formal para proceder con el pago fiduciario:',
      type: 'text',
      createdAt: '2026-04-02T14:33:00Z',
      read: true,
    },
    {
      id: 'm7',
      threadId: 'thread-001',
      senderId: 'u1',
      senderName: 'Carlos Mendoza',
      senderInitials: 'CM',
      content: '',
      type: 'quote',
      quote: {
        id: 'q-001',
        listingId: 'p1',
        listingTitle: 'Guitarra Eléctrica Fender Stratocaster Player Series',
        basePrice: 680,
        commissionRate: 0.05,
        commissionAmount: 34,
        sellerReceives: 646,
        buyerPays: 680,
        currency: 'USD',
        description: 'Venta de Fender Stratocaster Player Series Polar White + estuche rígido. Estado: como nuevo.',
        validUntil: '2026-04-09T23:59:00Z',
        status: 'pending',
      },
      createdAt: '2026-04-02T14:35:00Z',
      read: false,
    },
  ],
}
