export const FailureCode = Object.freeze({
  ENV_MISSING: 'ENV_MISSING',
  DB_MISSING_TABLE: 'DB_MISSING_TABLE',
  PURCHASE_NOT_CREATED: 'PURCHASE_NOT_CREATED',
  PAYOUT_AUDIT_FAILED: 'PAYOUT_AUDIT_FAILED',
  UNKNOWN: 'UNKNOWN',
})
